### ISSUE TITLE
Error with no valid BB Code parsing

### ISSUE THREAD

**Issue by laBecasse** [svenslaggare/BBCodeParser#6]
In node.js, I have a error when I typed

```
> var BBCodeParser = require('bbcode-parser');
undefined
> var parser = new BBCodeParser(BBCodeParser.defaultTags());
undefined
> parser.parseString('[b]Bold text[/b]');
'<b>Bold text</b>'
> parser.parseString('[]Bold text[/b]');
TypeError: Cannot read property 'isValid' of null
    at BBCodeParser.parseString (/tmp/node_modules/bbcode-parser/bbCodeParser.js:50:23)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
```

I solved it by changing `isValid` method in `bbCodeParserTree.js`, like that : 

```
    BBCodeParseTree.prototype.isValid = function () {                                              
        //An tree without subtrees is valid                                                          
        if (this.subTrees.length == 0) {                                                        
            return true;                                                                            
        }                                                                                       
        this.subTrees.forEach( function(value,i){                                          
            var currentTree = value//this.subTrees[i];                                    

            if ( currentTree == null || !currentTree.isValid()) {                                    
                return false;                                                                        
            }                                                                                        
        })                                                                                           

        return true;                                                                                 
    };  
```

Is this solution the good one ?

**Comment by ghost** [comment]
Sorry I solved it by changing `bbCodeparser.js` like this : 

```
   BBCodeParser.prototype.parseString = function (content, stripTags, insertLineBreak) {
        if (stripTags === void 0) { stripTags = false; }
        if (insertLineBreak === void 0) { insertLineBreak = true; }
        //Create the parse tree                                                                                                                                                                            
        var parseTree = BBCodeParseTree.buildTree(content, this.bbTags);
        //If the tree is invalid, return the input as text                                                                                                                                                 
        if (parseTree == null || !parseTree.isValid()) {
            return content;
        }
        //Convert it to HTML                                                                                                                                                                               
        return this.treeToHtml(parseTree.subTrees, insertLineBreak, stripTags);
    };
```

**Comment by svenslaggare** [comment]
Yes, the method should check for null, and has been updated to NPM.
